"""Data acquisition.

This package is the *only* part of the system that talks to the outside world.
The API and the web client read whatever the ETL has managed to load and never
fetch anything themselves.

Two rules shape everything in here:

1. A source that cannot be obtained produces a recorded failure, not a
   substitute. Tables are left empty and ``acquisition_runs`` explains why.
2. Anything synthetic is generated by :mod:`kaigyou_etl.sample`, registered
   under ``dataset_kind = 'sample'``, and carried through the API and UI as
   such.
"""
